//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSZYJYNLSL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_User
    {
        public string Id { get; set; }
        public string DepartmentId { get; set; }
        public string CompanyId { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string RowStatus { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreateId { get; set; }
        public string UpdateId { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
