



















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `SQLConnStringRead`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=192.168.1.65\MSSQLSERVER2008;database=WisdomClassed_JYNLSLOverall;user id=sa;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace SQLConnStringRead
{

	public partial class SQLConnStringReadDB : Database
	{
		public SQLConnStringReadDB() 
			: base("SQLConnStringRead")
		{
			CommonConstruct();
		}

		public SQLConnStringReadDB(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			SQLConnStringReadDB GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static SQLConnStringReadDB GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new SQLConnStringReadDB();
        }

		[ThreadStatic] static SQLConnStringReadDB _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        

		public class Record<T> where T:new()
		{
			public static SQLConnStringReadDB repo { get { return SQLConnStringReadDB.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public object Insert() { return repo.Insert(this); }

			public void Save() { repo.Save(this); }
			public int Update() { return repo.Update(this); }

			public int Update(IEnumerable<string> columns) { return repo.Update(this, columns); }
			public static int Update(string sql, params object[] args) { return repo.Update<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Update<T>(sql); }
			public int Delete() { return repo.Delete(this); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static bool Exists(string sql, params object[] args) { return repo.Exists<T>(sql, args); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(long skip, long take, string sql, params object[] args) { return repo.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(long skip, long take, Sql sql) { return repo.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }

		}

	}
	


    

	[TableName("dbo.CrmUser")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmUser : SQLConnStringReadDB.Record<CrmUser>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CompanyId")] 
		public string CompanyId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("DepartmentId")] 
		public string DepartmentId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("InnerUser")] 
		public int? InnerUser { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Code")] 
		public string Code { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Account")] 
		public string Account { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Password")] 
		public string Password { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Secretkey")] 
		public string Secretkey { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RealName")] 
		public string RealName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Spell")] 
		public string Spell { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Gender")] 
		public string Gender { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Birthday")] 
		public DateTime? Birthday { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Mobile")] 
		public string Mobile { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Telephone")] 
		public string Telephone { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("OICQ")] 
		public string OICQ { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Email")] 
		public string Email { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ChangePasswordDate")] 
		public DateTime? ChangePasswordDate { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("OpenId")] 
		public int? OpenId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("LogOnCount")] 
		public int? LogOnCount { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FirstVisit")] 
		public DateTime? FirstVisit { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("PreviousVisit")] 
		public DateTime? PreviousVisit { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("LastVisit")] 
		public DateTime? LastVisit { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AuditStatus")] 
		public string AuditStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AuditUserId")] 
		public string AuditUserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AuditUserName")] 
		public string AuditUserName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AuditDateTime")] 
		public DateTime? AuditDateTime { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsCityManager")] 
		public string IsCityManager { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Remark")] 
		public string Remark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Enabled")] 
		public int? Enabled { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SortCode")] 
		public int? SortCode { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.DocNotfPerson")]



	[PrimaryKey("Id")]



	[ExplicitColumns]
    public partial class DocNotfPerson : SQLConnStringReadDB.Record<DocNotfPerson>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public int Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Name")] 
		public string Name { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Pid")] 
		public string Pid { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FilePath")] 
		public string FilePath { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsJS")] 
		public string IsJS { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ContentId")] 
		public string ContentId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Title")] 
		public string Title { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Category")] 
		public string Category { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Publisher")] 
		public string Publisher { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ReleaseTime")] 
		public DateTime? ReleaseTime { get; set; }



}
    

	[TableName("dbo.ComNoticeAttach")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComNoticeAttach : SQLConnStringReadDB.Record<ComNoticeAttach>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ResourceId")] 
		public string ResourceId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileName")] 
		public string FileName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileReName")] 
		public string FileReName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileSize")] 
		public string FileSize { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsCompleted")] 
		public int? IsCompleted { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileAddress")] 
		public string FileAddress { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileType")] 
		public string FileType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileTypeName")] 
		public string FileTypeName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileRemark")] 
		public string FileRemark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime UpdateOn { get; set; }



}
    

	[TableName("dbo.ComNote")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComNote : SQLConnStringReadDB.Record<ComNote>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ResourcesId")] 
		public string ResourcesId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ReceivePhone")] 
		public string ReceivePhone { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("MistakeInfo")] 
		public string MistakeInfo { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ReceiveTime")] 
		public DateTime? ReceiveTime { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Status")] 
		public int? Status { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SendDate")] 
		public DateTime? SendDate { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Remark")] 
		public string Remark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComWhiteList")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComWhiteList : SQLConnStringReadDB.Record<ComWhiteList>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("PlateNumber")] 
		public string PlateNumber { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComOperationLog")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComOperationLog : SQLConnStringReadDB.Record<ComOperationLog>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("LogType")] 
		public int? LogType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Controller")] 
		public string Controller { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModelName")] 
		public string ModelName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Action")] 
		public string Action { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("HandleTypeId")] 
		public string HandleTypeId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Note")] 
		public string Note { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Ip")] 
		public string Ip { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Status")] 
		public int? Status { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComLoginLog")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComLoginLog : SQLConnStringReadDB.Record<ComLoginLog>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Source")] 
		public int? Source { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Ip")] 
		public string Ip { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Status")] 
		public int? Status { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Note")] 
		public string Note { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComAttributeValue")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComAttributeValue : SQLConnStringReadDB.Record<ComAttributeValue>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RsId")] 
		public string RsId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AttributeId")] 
		public int AttributeId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Value")] 
		public string Value { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComVisitRecord")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComVisitRecord : SQLConnStringReadDB.Record<ComVisitRecord>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Ip")] 
		public string Ip { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("BrowerName")] 
		public string BrowerName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("BrowerVersion")] 
		public string BrowerVersion { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Os")] 
		public string Os { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("langage")] 
		public string langage { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmCompany")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmCompany : SQLConnStringReadDB.Record<CrmCompany>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ParentId")] 
		public string ParentId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Category")] 
		public string Category { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Code")] 
		public string Code { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FullName")] 
		public string FullName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ShortName")] 
		public string ShortName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Nature")] 
		public string Nature { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Manager")] 
		public string Manager { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Contact")] 
		public string Contact { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Phone")] 
		public string Phone { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Fax")] 
		public string Fax { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Email")] 
		public string Email { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ProvinceId")] 
		public string ProvinceId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Province")] 
		public string Province { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CityId")] 
		public string CityId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("City")] 
		public string City { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CountyId")] 
		public string CountyId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("County")] 
		public string County { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Address")] 
		public string Address { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AccountInfo")] 
		public string AccountInfo { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Postalcode")] 
		public string Postalcode { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Web")] 
		public string Web { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Remark")] 
		public string Remark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Enforcement")] 
		public int? Enforcement { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Enabled")] 
		public int? Enabled { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SortCode")] 
		public int? SortCode { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("DeleteMark")] 
		public int? DeleteMark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateDate")] 
		public DateTime? CreateDate { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateUserId")] 
		public string CreateUserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateUserName")] 
		public string CreateUserName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModifyDate")] 
		public DateTime? ModifyDate { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModifyUserId")] 
		public string ModifyUserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModifyUserName")] 
		public string ModifyUserName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComAttribute")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComAttribute : SQLConnStringReadDB.Record<ComAttribute>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RsId")] 
		public string RsId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AttributeId")] 
		public int AttributeId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AttributeName")] 
		public string AttributeName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("DateType")] 
		public string DateType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RegExpression")] 
		public string RegExpression { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ListSql")] 
		public string ListSql { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("OrderNo")] 
		public int? OrderNo { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComFileIsUse")]



	[ExplicitColumns]
    public partial class ComFileIsUse : SQLConnStringReadDB.Record<ComFileIsUse>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("IsUse")] 
		public int? IsUse { get; set; }



}
    

	[TableName("dbo.ComNotice")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComNotice : SQLConnStringReadDB.Record<ComNotice>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Title")] 
		public string Title { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Contents")] 
		public string Contents { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Astatus")] 
		public int? Astatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsTop")] 
		public int? IsTop { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AType")] 
		public int? AType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("StartTime")] 
		public DateTime? StartTime { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("EndTimie")] 
		public DateTime? EndTimie { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComResource")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComResource : SQLConnStringReadDB.Record<ComResource>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ParentId")] 
		public string ParentId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RsKey")] 
		public string RsKey { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RsValue")] 
		public string RsValue { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RsUseflg")] 
		public string RsUseflg { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RsRemark")] 
		public string RsRemark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("OrderNo")] 
		public int? OrderNo { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComNoticeReceive")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComNoticeReceive : SQLConnStringReadDB.Record<ComNoticeReceive>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("NoticeId")] 
		public string NoticeId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UserId")] 
		public string UserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UserNameq")] 
		public string UserNameq { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsRead")] 
		public int? IsRead { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("LastReadTime")] 
		public DateTime? LastReadTime { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComArticle")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComArticle : SQLConnStringReadDB.Record<ComArticle>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Title")] 
		public string Title { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Contents")] 
		public string Contents { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Astatus")] 
		public string Astatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("StartTime")] 
		public DateTime? StartTime { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("EndTimie")] 
		public DateTime? EndTimie { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmIdeaList")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmIdeaList : SQLConnStringReadDB.Record<CrmIdeaList>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ResourceID")] 
		public string ResourceID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Type")] 
		public string Type { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UserId")] 
		public string UserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Idea")] 
		public string Idea { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ProcessID")] 
		public string ProcessID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ProcessInstanceID")] 
		public string ProcessInstanceID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("WorkList")] 
		public string WorkList { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("LeveL")] 
		public int? LeveL { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Duty")] 
		public string Duty { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsSync")] 
		public byte[] IsSync { get; set; }



}
    

	[TableName("dbo.ComAttachment")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComAttachment : SQLConnStringReadDB.Record<ComAttachment>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ResourceId")] 
		public string ResourceId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileName")] 
		public string FileName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileReName")] 
		public string FileReName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileSize")] 
		public string FileSize { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsCompleted")] 
		public int? IsCompleted { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileAddress")] 
		public string FileAddress { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileType")] 
		public string FileType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileTypeName")] 
		public string FileTypeName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FileRemark")] 
		public string FileRemark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmOpinions")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmOpinion : SQLConnStringReadDB.Record<CrmOpinion>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Contents")] 
		public string Contents { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("OpType")] 
		public string OpType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmUserSign")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmUserSign : SQLConnStringReadDB.Record<CrmUserSign>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UserId")] 
		public string UserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SignType")] 
		public string SignType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SignAddress")] 
		public string SignAddress { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmPost")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmPost : SQLConnStringReadDB.Record<CrmPost>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CompanyId")] 
		public string CompanyId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("DepartmentId")] 
		public string DepartmentId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RoleId")] 
		public string RoleId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Code")] 
		public string Code { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FullName")] 
		public string FullName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Remark")] 
		public string Remark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Enabled")] 
		public int? Enabled { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SortCode")] 
		public int? SortCode { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmRoleMenu")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmRoleMenu : SQLConnStringReadDB.Record<CrmRoleMenu>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("MenuId")] 
		public string MenuId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RoleId")] 
		public string RoleId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmRole")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmRole : SQLConnStringReadDB.Record<CrmRole>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CompanyId")] 
		public string CompanyId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Category")] 
		public string Category { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Code")] 
		public string Code { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FullName")] 
		public string FullName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Remark")] 
		public string Remark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Enabled")] 
		public int? Enabled { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SortCode")] 
		public int? SortCode { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmIssuanceModel")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmIssuanceModel : SQLConnStringReadDB.Record<CrmIssuanceModel>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModelIdentify")] 
		public string ModelIdentify { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModelName")] 
		public string ModelName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModelType")] 
		public int? ModelType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModelAddress")] 
		public string ModelAddress { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModelWidth")] 
		public int? ModelWidth { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ModelHeight")] 
		public int? ModelHeight { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("PictureSets")] 
		public string PictureSets { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("StoredProcedure")] 
		public string StoredProcedure { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmUserMenu")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmUserMenu : SQLConnStringReadDB.Record<CrmUserMenu>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("MenuId")] 
		public string MenuId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UserId")] 
		public string UserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComMenu")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComMenu : SQLConnStringReadDB.Record<ComMenu>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("MenuName")] 
		public string MenuName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ParentMenuId")] 
		public string ParentMenuId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Controller")] 
		public string Controller { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Action")] 
		public string Action { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("MenuUrl")] 
		public string MenuUrl { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("MenuLevel")] 
		public int? MenuLevel { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsMenu")] 
		public int IsMenu { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("MenuDesc")] 
		public string MenuDesc { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IconPic")] 
		public string IconPic { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("OpenType")] 
		public int? OpenType { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SortCode")] 
		public int? SortCode { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmMessageWork")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmMessageWork : SQLConnStringReadDB.Record<CrmMessageWork>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Titles")] 
		public string Titles { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ProcessInstanceID")] 
		public string ProcessInstanceID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SendActivityID")] 
		public string SendActivityID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ActivityInstanceID")] 
		public string ActivityInstanceID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("StartDate")] 
		public DateTime StartDate { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SenderID")] 
		public string SenderID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ExecuteDate")] 
		public DateTime? ExecuteDate { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ActionerID")] 
		public string ActionerID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FormID")] 
		public string FormID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FormData")] 
		public string FormData { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FormAddress")] 
		public string FormAddress { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ContentTypeID")] 
		public string ContentTypeID { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("IsReply")] 
		public int IsReply { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("State")] 
		public int State { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Note")] 
		public string Note { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmDepartment")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmDepartment : SQLConnStringReadDB.Record<CrmDepartment>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CompanyId")] 
		public string CompanyId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ParentId")] 
		public string ParentId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Code")] 
		public string Code { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FullName")] 
		public string FullName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ShortName")] 
		public string ShortName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Nature")] 
		public string Nature { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Manager")] 
		public string Manager { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Address")] 
		public string Address { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Phone")] 
		public string Phone { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Fax")] 
		public string Fax { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Email")] 
		public string Email { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Remark")] 
		public string Remark { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Enabled")] 
		public int? Enabled { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SortCode")] 
		public int? SortCode { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.CrmUserRole")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmUserRole : SQLConnStringReadDB.Record<CrmUserRole>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UserId")] 
		public string UserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RoleId")] 
		public string RoleId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComHolidays")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComHoliday : SQLConnStringReadDB.Record<ComHoliday>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("HostDate")] 
		public DateTime? HostDate { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}
    

	[TableName("dbo.ComNoteContent")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class ComNoteContent : SQLConnStringReadDB.Record<ComNoteContent>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ReceivePhone")] 
		public string ReceivePhone { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("MistakeInfo")] 
		public string MistakeInfo { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ReceiveTime")] 
		public DateTime? ReceiveTime { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("SendPerson")] 
		public string SendPerson { get; set; }



}
    

	[TableName("dbo.DocumentNotification")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class DocumentNotification : SQLConnStringReadDB.Record<DocumentNotification>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Title")] 
		public string Title { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Publisher")] 
		public string Publisher { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("ReleaseTime")] 
		public DateTime? ReleaseTime { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("AplayState")] 
		public string AplayState { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Category")] 
		public string Category { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("GGContent")] 
		public string GGContent { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Sendname")] 
		public string Sendname { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("FilePath")] 
		public string FilePath { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Iszd")] 
		public string Iszd { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Xh")] 
		public int Xh { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("JieShouCount")] 
		public int? JieShouCount { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("JieShouAllCount")] 
		public int? JieShouAllCount { get; set; }



}
    

	[TableName("dbo.CrmFeedBack")]



	[PrimaryKey("Id", AutoIncrement=false)]

	[ExplicitColumns]
    public partial class CrmFeedBack : SQLConnStringReadDB.Record<CrmFeedBack>  
    {



		/// <summary>
        /// 
        /// </summary>
		[Column("Id")] 
		public string Id { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Idea")] 
		public string Idea { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UserId")] 
		public string UserId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UserName")] 
		public string UserName { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("RowStatus")] 
		public int? RowStatus { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("Version")] 
		public byte[] Version { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreatorId")] 
		public string CreatorId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateBy")] 
		public string CreateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("CreateOn")] 
		public DateTime? CreateOn { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateId")] 
		public string UpdateId { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateBy")] 
		public string UpdateBy { get; set; }





		/// <summary>
        /// 
        /// </summary>
		[Column("UpdateOn")] 
		public DateTime? UpdateOn { get; set; }



}


}


